spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

ai:
  service:
    base-url: ${AI_SERVICE_BASE_URL:http://localhost:8000}
